steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--prefix', 'server']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--prefix', 'client']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/irur-phase1', '.']
images:
- 'gcr.io/$PROJECT_ID/irur-phase1'
